version: "3.9"
services:
  postgres:
    container_name: "MySQL_ims"
    image: mysql:8.4.3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - "3308:3306"
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    labels:
      org.springframework.boot.service-connection: mysql
    profiles:
      - dev
volumes:
  db:
    driver:
      local